### ISSUE TITLE
Branching Advice

### ISSUE THREAD

**Issue by jonleesy** [kymckay/f28cd-project#9]
Not sure if this is the way to raise a discussion but here it goes. 🤣

I'm confused on how to branch out to work on a particular section, say politician section. Do I branch off the header branch, given that the main layout has already been setup? Or do I just create a new branch off main and adapt Politician Section when merging eventually?

**Comment by kymckay** [comment]
It's a reasonable question because in all honesty there's no right answer between these two (and there will likely be some merging to do at the end either way).

Personally in this case I'd probably branch off of the header branch since the project is so early and it has established some page structure. In a perfect workflow the header would be in a stable state and a PR opened at that point without further work continuing on that branch (unrelated functionality can be worked on branching from there).

**Comment by kymckay** [comment]
And yeah feel free to raise questions here! 👍
